general {
    colors = true
    interval = 5
}

order += "ethernet _first_"
order += "disk /"
order += "load"
order += "memory"
order += "volume master"
order += "tztime local"

ethernet _first_ {
    format_up = "ETH: %ip"
    format_down = "ETH: down"
}

disk "/" {
    format = "ROOT: %used/%avail"
}

load {
    format = "CPU: %1min"
}

memory {
    format = "RAM: %used/%available"
    threshold_degraded = "1G"
    format_degraded = "MEMORY < %available"
}

volume master {
    format = "VOL: %volume"
    format_muted = "VOL: muted (%volume)"
    device = "default"
    mixer = "Master"
    mixer_idx = 0
}

tztime local {
    format = "%Y-%m-%d %H:%M:%S"
}

